# set board specs
BOARD_TAG = uno

# used libraries werkt aleen voor include van arduino.mk
ARDUINO_LIBS = Adafruit_GFX  Adafruit_ILI9341 SPI
USER_LIB_PATH = libraries/

include /usr/share/arduino/Arduino.mk

# device_path werkt aleen na de include van arduino.mk
DEVICE_PATH = /dev/ttyS3        # n is COM port number

